name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Sync files to EC2
        run: |
          rsync -avz --exclude ".git" ./ ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/complain-sg

      - name: Deploy on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ubuntu/complain-sg/backend
          # Ensure Poetry is installed
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

          # Install dependencies from pyproject.toml
          poetry install --no-root

          # Restart FastAPI server with uvicorn in tmux
          tmux kill-session -t complain-sg 2>/dev/null
          tmux new -d -s complain-sg "poetry run uvicorn server:app --host 0.0.0.0 --port 8000"
          EOF
